# Use an official PostgreSQL image as a parent image
FROM postgres:12

# Set environment variables
ENV POSTGRES_DB=your_database_name
ENV POSTGRES_USER=your_database_user
ENV POSTGRES_PASSWORD=your_database_password

# Expose PostgreSQL port
EXPOSE 5432
